patch-turbo:

  stage: validate

  # needs:
  #   - yarn

  script:

    # In case Corepack isn't enabled in Node.js, we have to do that here.
    - corepack enable
    # At the time of writing, the Node.js in Drupal.org GitLab CI is 18.x, which
    # doesn't have the 'corepack use' command that newer versions of Corepack
    # offer so we have to explicitly set a Yarn version here. Note that this
    # upgrades the global Yarn so that we can install the local Yarn in the next
    # step. The default version of Yarn is 1.x which doesn't understand the
    # 'yarn set' command and will fail.
    #
    # @see https://nodejs.org/docs/latest-v18.x/api/corepack.html
    - corepack prepare yarn@4.5.0 --activate
    # Now that the global Yarn understands the 'yarn set' command, set the local
    # Yarn to 4.x.
    - yarn set version 4.5.0
    # When Yarn detects it's running in a CI environment, it defaults to
    # --immutable which would cause our yarn install to fail with an error since
    # we don't currently ship with a yarn.lock; this tells Yarn to not do that.
    - yarn install --no-immutable

    # Extract an unpatched copy of Turbo.
    - yarn workspace drupal-refreshless-turbo vendorize

    # Validate that we can patch Turbo without failures.
    - yarn workspace drupal-refreshless-turbo patch-turbo
