ai_vdb_provider_milvus.settings:
  type: config_object
  label: 'Milvus Settings'
  mapping:
    api_key:
      type: string
      label: 'API Key'
      required: true
    server:
      type: string
      label: 'Server'
      required: true
    port:
      type: integer
      label: 'Port'
      required: false
