# Schema for the configuration files of the "DSFR for Drupal" theme.

dsfr4drupal.settings:
  type: theme_settings
  label: 'DSFR for Drupal settings'
  mapping:
    logo_text:
      type: label
      label: 'Logo text'
    logo_operator:
      type: integer
      label: 'Logo operator (file ID)'
    mourning_mode:
      type: boolean
      label: 'Enable mourning mode'
    production:
      type: boolean
      label: Production mode
    verbose:
      type: boolean
      label: Verbose mode
    level:
      type: string
      label: 'Log level'
    scheme:
      type: string
      label: 'Theme'
    scheme_choose:
      type: boolean
      label: 'Enable display settings'
    mega_menu:
      type: boolean
      label: 'Use mega menu'
    container_class:
      type: string
      label: 'Container'
    form_novalidate:
      type: boolean
      label: 'Disable browser validation of form fields'
    form_description_tooltip:
      type: boolean
      label: 'Show help texts as tooltip'
    footer_copy:
      type: text_format
      label: 'Copyright notice'
    show_password_button:
      type: boolean
      label: 'Enable "Show password" feature'
