ai_provider_anythingllm.settings:
  type: config_object
  label: 'AnythingLLM Settings'
  mapping:
    api_url:
      type: string
      label: 'API URL'
      required: true
    api_key:
      type: string
      label: 'API Key'
      required: true
