<?php

/**
 * @file
 * UI Patterns Blocks custom add-ons.
 */

/**
 * Implements hook_plugin_filter_TYPE__CONSUMER_alter().
 */
function ui_patterns_blocks_plugin_filter_block__layout_builder_alter(array &$definitions, array $extra) : void {
  foreach ($definitions as $id => $definition) {
    if ($definition['provider'] === 'ui_patterns_blocks' &&
      (!array_key_exists("context_definitions", $definition) ||
        !is_array($definition['context_definitions']) ||
        !array_key_exists("entity", $definition['context_definitions']))) {
      // In Layout builder,
      // we remove all blocks defined by ui_patterns_blocks
      // which do not declare  entity in context_definitions.
      unset($definitions[$id]);
    }
  }
}

/**
 * Implements hook_plugin_filter_TYPE_alter().
 */
function ui_patterns_blocks_plugin_filter_block_alter(array &$definitions, array $extra, ?string $consumer)  : void {
  if ($consumer !== 'layout_builder') {
    foreach ($definitions as $id => $definition) {
      if ($definition['provider'] === 'ui_patterns_blocks' && array_key_exists("context_definitions", $definition)
          &&  array_key_exists("entity", $definition['context_definitions'])) {
        // In all User interfaces except Layout builder,
        // we remove blocks defined by ui_patterns_blocks
        // which declare entity in context_definitions.
        unset($definitions[$id]);
      }
    }
  }
}
