<?php

/**
 * @file
 * Contains listjs_cdn_alter.module.
 */

/**
 * Implements hook_library_info_alter().
 */
function listjs_cdn_alter_library_info_alter(&$libraries, $module) {
  if ($module == "listjs") {
    unset($libraries['listjs']['js']['/libraries/listjs/dist/list.min.js']);
    $libraries['listjs']['js']['//cdnjs.cloudflare.com/ajax/libs/list.js/1.0.2/list.min.js'] = [
      'type' => 'external',
      'minified' => TRUE,
    ];
  }
}
